### ISSUE TITLE
Show cell with UIRefreshControl on lazy load 

### ISSUE THREAD

**Issue by jaredStef** [alchimya/iOS-LazyTableView#1]
I think this project would be even better if when you scrolled to the bottom and it was lazily loading the next items it added a cell with a UIRefreshControl similar to Twitter

**Comment by alchimya** [comment]
Hi Jared,
there are many ways to implement a lazy loading data, such as pull to refresh, load more button at the bottom and so on, but the **main purpose** of this UITableView subclass was to implement an **infinite scroll behaviour**, so the main goal was to develop an UITableView that raise an event when the last item (at bottom) has been shown.
Regards,
Domenico

**Comment by jaredStef** [comment]
Ok thanks for the responce! Get project @alchimya

**Comment by jaredStef** [comment]
*great project
